spring:
  cache:
    jcache:
      config: classpath:resources/CacheManager.xml;
  datasource:
    url: jdbc:mysql://localhost:3306/test
    name: test
    password: test
    driver-class-name: com.mysql.jdbc.Driver
